### ISSUE TITLE
Delete item

### ISSUE THREAD

**Issue by abashmak** [openpassphrase/opp-web#147]
Currently there's no way to delete a single entry item, only the whole category. The API provides the capability to do this: https://openpassphrase.com/api_ref.html#delete-item

**Comment by DmitryEfimenko** [comment]
ops. Not sure when this got broken, but the issue is due to [this line of code](https://github.com/openpassphrase/opp-web/blob/25a80a4504da8728690d21c37e182a59a0745c5b/src/app/content/components/item/item.component.html#L62).

It should be `gap-2` instead of `gap-20`.

Feel free to apply the fix!
