### ISSUE TITLE
Feature request - progressive web app for mobile

### ISSUE THREAD

**Issue by abashmak** [openpassphrase/opp-web#43]
This is a request to refactor the site to be mobile friendly with option to store state on a mobile device shortcut, so that it behaves much like a native app. The following features are requested:

1. Ability to specify how long the login session lasts (in hours or days)
2. Ability to log out
3. Ability to search items within collapsed categories (search box)
4. Initial screen shows a list of collapsed categories
5. Clicking on a collapsed category pops up new screen with expanded list
6. Sorting of categories (as a settings option or toggle button) (very nice to have)
7. Sorting of items within category (as a settings option or toggle button) (nice to have)

**Comment by DmitryEfimenko** [comment]
for PWA I need a set of app icons in the following sizes:
![pwa-icons](https://user-images.githubusercontent.com/2098175/44669934-30b40600-a9d6-11e8-8e5e-ccc02f6f8f2c.PNG)

**Comment by abashmak** [comment]
Done. Pull latest from master, there's an icons folder at the root level.

**Comment by abashmak** [comment]
Agree on 1 and 5 and agree that this issue can be closed. Will open up 3, 6, 7 as separate issues.
