### ISSUE TITLE
Feature request - Implement content-security-policy header

### ISSUE THREAD

**Issue by abashmak** [openpassphrase/opp-web#47]
Protect PWA against XSS using [CSP](https://developers.google.com/web/fundamentals/security/csp/)

**Comment by DmitryEfimenko** [comment]
You might want to implement an API on the server for CSP reporting. For example, it could send you an email with CSP report details.
See [details here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#Enabling_reporting)
