### ISSUE TITLE
Sorting of items

### ISSUE THREAD

**Issue by abashmak** [openpassphrase/opp-web#49]
As a user I'd like to be able switch between having the list of items within a category sorted alphabetically or displayed in default order (as they were added). This setting needs to persist across sessions.

**Comment by DmitryEfimenko** [comment]
is that a global setting - one per all items or a category-specific setting?
Basically, is there just one single checkbox "sort all items" somewhere above all categories or is there a checkbox per category and when checked sorts items only inside that category?

**Comment by DmitryEfimenko** [comment]
I think the second one... category-specific.

**Comment by abashmak** [comment]
I don't think it makes sense to make it item sorting a category-level setting. I figure if you prefer the items sorted in one category, then all the others should be sorted also.

I wonder if maybe it's easier to just always display everything (category/items) sorted. Is there a compelling argument some user might prefer the original order?

**Comment by DmitryEfimenko** [comment]
You're probably right. Besides having separate controls for sorting categories and items clutters the UI. In addition, our filtering functionality reduces the need for sorting anyway. I'll implement sorting of categories and items via a single control

**Comment by DmitryEfimenko** [comment]
oh, I misread your suggestion. You are thinking of just displaying them sorted at all times. Sure, we can do that. I don't really see a reason why anybody would prefer to keep original sort order. So, decided? Do that?

**Comment by abashmak** [comment]
For the items yes, let's keep them always sorted. For the categories, I'm now thinking it's useful to have the ability to toggle between sorted or default.

**Comment by DmitryEfimenko** [comment]
I understand that some categories might be more important or more often used than others. However, there is no guarantee that the user will be adding categories in the order of importance. Really, what you want is an ability to set a custom order of categories.

**Comment by abashmak** [comment]
Yes, that would be amazing, if I could drag and drop the categories into the order that I want. But I figure that's too much to ask.

**Comment by abashmak** [comment]
Should we combine this with #48?

**Comment by DmitryEfimenko** [comment]
yes, we should

**Comment by abashmak** [comment]
Closing and moving to #62
