### ISSUE TITLE
Feature: display passwords as ****

### ISSUE THREAD

**Issue by DmitryEfimenko** [openpassphrase/opp-web#78]
By default (which could be configurable per account) the passwords should be shown as ****.
Clicking on the starts would copy the actual password into the clipboard.
A button with an "eye" icon next to it would reveal the actual password.

This is especially handy when you're using OPP on a desktop in a public setting (for example, at work) where there is a risk of someone looking over your shoulder.

Thoughts?

**Comment by abashmak** [comment]
Great idea! Let's do it. I don't even think it needs to be configurable. Let's just default to showing partially obscured password with an "eye" option to look it up.
